name: 'Deploy to AWS s3'
description: 'Deploy'
runs:
  using: 'docker'
  image: 'dockerfile'
inputs:
  bucket:
    description: 'The S3 bucket name'
    required: true
  bucket-region:
    description: 'The region of the S3 region'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder containg the deployable files'
    required: true
outputs:
  website-url:
    desciption: "The url of the live website"