name: Event 1
on:
  pull_request: 
    types:
      - opened # Run on opened pull request
  workflow_dispatch:
  push:
    branches:
      - main
      - "dev/*" # * means any characters _except_ slashes
      - "feature/**" # ** means any characters _including_ slashes
    paths: '.github/workflows/*' # Run if any file changes in this path
    paths-ignore: 'public/*' # If any file in this path is changed, the workflow will not be run
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependecies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo: "Deploying..."