name: Lint, test and deploy code
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
      - name: Lint the code
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Test the code
        run: npm run test
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Build the code
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
