name: Reusable-deploy
on: 
  workflow_call:
    inputs: 
      artifact-name:
        description: The name of the deployable artifact files
        required: true
        default: dist
        type: string
    secrets: 
      some-secrets:
        required: false
    outputs:
      result:
        description: The result of the deploy
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.deploy-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with: 
          name: ${{ inputs.artifact-name }}
      - name: List dist files
        run: ls
      - name: Output information
        id: deploy
        run: echo "Deploying..."
      - name: Set result output
        id: set-result
        run: echo "deploy-result='Success'" >> $GITHUB_OUTPUT
